In [372]:
import numpy as np
import pandas as pd
import csv
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [373]:
#col_names = ['id', 'quote', 'author', 'category']
df = pd.read_csv('/content/format2.csv', index_col = False) 

In [374]:
df.sort_values(by = ['id'], inplace = True)

In [375]:
df.columns

Index(['id', 'quote', 'author', 'category'], dtype='object')

In [376]:
df = df.reset_index()

In [377]:
df.drop(['index'],axis = 1, inplace = True)

In [378]:
df.head(5)

id                                              quote         author  \
0   1  By definition all scientists are data scientis...  Monica Rogati   
1   2  Possessed' is probably the right word. I often...  Jennifer Shin   
2   3  I think of data science as more like a practic...      Bob Hayes   
3   4  As a data scientist, I can predict what is lik...  Bill Schmarzo   
4   5  Data scientists are kind of like the new Renai...   John Foreman   

       category  
0  Data Science  
1  Data Science  
2  Data Science  
3  Data Science  
4  Data Science

In [379]:
df.quote

0      By definition all scientists are data scientis...
1      Possessed' is probably the right word. I often...
2      I think of data science as more like a practic...
3      As a data scientist, I can predict what is lik...
4      Data scientists are kind of like the new Renai...
                             ...                        
159    Is artificial intelligence less than our intel...
160    By far, the greatest danger of Artificial Inte...
161    The sad thing about artificial intelligence is...
162    Forget artificial intelligence – in the brave ...
163    Before we work on artificial intelligence why ...
Name: quote, Length: 164, dtype: object

In [380]:
df.shape

(164, 4)

In [381]:
features = ['quote', 'author', 'category']

In [382]:
df1 = df['author'].str.split(' ', expand = True)
df['author'] = df1[0] + df1[1]

In [383]:
# df.drop(['author'], axis = 1, inplace = True)

In [384]:
df.head(5)

id                                              quote        author  \
0   1  By definition all scientists are data scientis...  MonicaRogati   
1   2  Possessed' is probably the right word. I often...  JenniferShin   
2   3  I think of data science as more like a practic...      BobHayes   
3   4  As a data scientist, I can predict what is lik...  BillSchmarzo   
4   5  Data scientists are kind of like the new Renai...   JohnForeman   

       category  
0  Data Science  
1  Data Science  
2  Data Science  
3  Data Science  
4  Data Science

In [385]:
df.isnull().sum()

id          0
quote       0
author      3
category    0
dtype: int64

In [386]:
df.dropna(inplace = True)

In [387]:
combine = df['quote'].str.lower() + ' ' + df['author'].str.lower() + ' ' + df['category'].str.lower()

In [388]:
print(combine)

0      by definition all scientists are data scientis...
1      possessed' is probably the right word. i often...
2      i think of data science as more like a practic...
3      as a data scientist, i can predict what is lik...
4      data scientists are kind of like the new renai...
                             ...                        
159    is artificial intelligence less than our intel...
160    by far, the greatest danger of artificial inte...
161    the sad thing about artificial intelligence is...
162    forget artificial intelligence – in the brave ...
163    before we work on artificial intelligence why ...
Length: 161, dtype: object


In [407]:
from sklearn.feature_extraction import text
my_stop_words = text.ENGLISH_STOP_WORDS.union(["book"])
vectorize = TfidfVectorizer(ngram_range=(1,1), stop_words=my_stop_words)

In [408]:
feature_vectors = vectorize.fit_transform(combine)

In [409]:
print(feature_vectors)

  (0, 1086)	0.09533039704446845
  (0, 833)	0.18488884908820388
  (0, 355)	0.21214835829823603
  (0, 1126)	0.21214835829823603
  (0, 465)	0.21214835829823603
  (0, 473)	0.21214835829823603
  (0, 1160)	0.21214835829823603
  (0, 223)	0.21214835829823603
  (0, 806)	0.21214835829823603
  (0, 224)	0.21214835829823603
  (0, 646)	0.15762933987817176
  (0, 980)	0.19620256762230426
  (0, 156)	0.1689430584122721
  (0, 1304)	0.15299726773634031
  (0, 56)	0.21214835829823603
  (0, 567)	0.21214835829823603
  (0, 571)	0.42429671659647206
  (0, 889)	0.19620256762230426
  (0, 316)	0.2088399811412263
  (0, 1089)	0.29021091887709677
  (0, 339)	0.21214835829823603
  (1, 684)	0.2012702375135048
  (1, 495)	0.18614208331787507
  (1, 332)	0.18614208331787507
  (1, 849)	0.1172731467956762
  :	:
  (158, 36)	0.1601418681092131
  (158, 652)	0.3508344801187029
  (158, 87)	0.1788691041812127
  (159, 1262)	0.3766766107215666
  (159, 609)	0.3766766107215666
  (159, 145)	0.3766766107215666
  (159, 755)	0.3483643181576

In [410]:
similar = cosine_similarity(feature_vectors)

In [411]:
print(similar)

[[1.         0.06379227 0.09452393 ... 0.         0.02581279 0.        ]
 [0.06379227 1.         0.14375579 ... 0.         0.03265229 0.03505957]
 [0.09452393 0.14375579 1.         ... 0.         0.03558586 0.        ]
 ...
 [0.         0.         0.         ... 1.         0.15940288 0.16598562]
 [0.02581279 0.03265229 0.03558586 ... 0.15940288 1.         0.15051089]
 [0.         0.03505957 0.         ... 0.16598562 0.15051089 1.        ]]


In [412]:
similar.shape

(161, 161)

In [414]:
quote = input('Enter the quote: ').lower()

Enter the quote: Data analysts who don't organize their transformation pipelines often end up not being able to repeat their analyses, so the advice I would give to myself is the same advice often given to traditional scientists: make your experiments repeatable!


In [415]:
quote_all = df['quote'].tolist()
print(quote_all)

["By definition all scientists are data scientists. In my opinion, they are half hacker, half analyst, they use data to build products and find insights. It's Columbus meet Columbo―starry-eyed explorers and skeptical detectives.", "Possessed' is probably the right word. I often tell people, I don't want to necessarily be a data scientist. You just kind of are a data scientist. You just can't help but look at that data set and go, I feel like I need to look deeper. I feel like that's not the right fit.'", "I think of data science as more like a practice than a job. Think of the scientific method, where you have to have a problem statement, generate a hypothesis, collect data, analyze data and then communicate the results and take action…. If you just use the scientific method as a way to approach data-intensive projects, I think you're more apt to be successful with your outcome.", "As a data scientist, I can predict what is likely to happen, but I cannot explain why it is going to happ

In [416]:
close_match = difflib.get_close_matches(quote, quote_all)
print(close_match)

["Data analysts who don't organize their transformation pipelines often end up not being able to repeat their analyses, so the advice I would give to myself is the same advice often given to traditional scientists: make your experiments repeatable!"]


In [417]:
close = close_match[0]

In [418]:
id_of_quote = df[df.quote == close]['id'].values[0]
print(id_of_quote)

32


In [419]:
similarity_score = list(enumerate(similar[id_of_quote]))
print(similarity_score)

[(0, 0.08133406358475433), (1, 0.11959319649935159), (2, 0.175088763371139), (3, 0.11827030650652971), (4, 0.09651881511356894), (5, 0.08326062717257457), (6, 0.07327073132155172), (7, 0.09304905618915439), (8, 0.1307190705403647), (9, 0.11125168917326428), (10, 0.08176483459004591), (11, 0.061634864127629765), (12, 0.07538609122044979), (13, 0.04994644691997388), (14, 0.10147636115529617), (15, 0.0866222088771468), (16, 0.06089573870758331), (17, 0.06396529630657043), (18, 0.06274527037619929), (19, 0.14681915598855327), (20, 0.13596426087856475), (21, 0.05991187440302776), (22, 0.08551543416901553), (23, 0.11351731793237987), (24, 0.08338547397466992), (25, 0.08644124398527057), (26, 0.03682596100367181), (27, 0.14458263331506482), (28, 0.07809288368646568), (29, 0.13800141016096046), (30, 0.07927472360715881), (31, 0.05137501079729454), (32, 0.9999999999999998), (33, 0.09891643449220477), (34, 0.034770442269758006), (35, 0.17027825777491506), (36, 0.0), (37, 0.0), (38, 0.0), (39, 0.

In [420]:
len(similarity_score)

161

In [421]:
sorted_sim_quote = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_sim_quote)

[(32, 0.9999999999999998), (2, 0.175088763371139), (35, 0.17027825777491506), (135, 0.15350053575758707), (19, 0.14681915598855327), (27, 0.14458263331506482), (121, 0.13827511677255244), (29, 0.13800141016096046), (20, 0.13596426087856475), (8, 0.1307190705403647), (92, 0.12960967468446963), (131, 0.12935981887436257), (144, 0.12149564314565076), (1, 0.11959319649935159), (133, 0.11913882618139043), (3, 0.11827030650652971), (50, 0.11670793487827083), (99, 0.11641225399369312), (137, 0.11439284832302349), (23, 0.11351731793237987), (101, 0.1124937925798643), (9, 0.11125168917326428), (126, 0.11114399306822319), (129, 0.10468854971759867), (134, 0.10360331756431078), (14, 0.10147636115529617), (127, 0.10136771433698591), (33, 0.09891643449220477), (132, 0.09786405011621468), (128, 0.09679321375209447), (4, 0.09651881511356894), (39, 0.09621099208353469), (136, 0.09427787233242363), (7, 0.09304905618915439), (95, 0.08906863402370085), (15, 0.0866222088771468), (25, 0.08644124398527057),

In [422]:
id = quote[0]
print(id)

d


In [423]:
print('Suggested quotes are:')
i = 1
for quote in sorted_sim_quote:
  try:
    if i == 1:
      i = i+1
      continue
    id = quote[0]
    quote_from_id = df[df.id==id]['quote'].values[0]
    print(i-1, ') ', quote_from_id, sep = '')
    i = i+1
    if(i==7):
      break
  except:
    pass

# for quote in range(0,6):
#   try:
#     id = sorted_sim_quote[quote]
#     quote_from_id = df[df.id==id[0]]['quote'].values[0]
#     # if(i < 5):
#     print(quote+1, ') ', quote_from_id, sep = '')
#   except:
#     print(id)
#     pass
  

Suggested quotes are:
1) Possessed' is probably the right word. I often tell people, I don't want to necessarily be a data scientist. You just kind of are a data scientist. You just can't help but look at that data set and go, I feel like I need to look deeper. I feel like that's not the right fit.'
2) The difference between a great [data scientist] and a good one is like the difference between lightning and a lightning bug.
3) Data is a precious thing and will last longer than the systems themselves.
4) Data science's learning curve is formidable. To a great degree, you will need a degree, or something substantially like it, to prove you're committed to this career….
5) What makes a good scientist great is creativity with data, skepticism and good communication skills. Getting all of that together in the same person is difficult―because traditionally, different people follow different paths in their careers―some are more technical, others are more creative and communicative. A data sc

In [424]:
import pickle
pickle.dump(similar, open('model.pkl', 'wb'))